# Generated by Django 2.2.9 on 2020-01-15 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200115_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 12, 48, 29, 522138, tzinfo=utc)),
        ),
    ]
