# Generated by Django 2.2.9 on 2020-01-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='user',
            new_name='users',
        ),
    ]
