# Generated by Django 2.2.9 on 2020-01-16 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20200115_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
